#!/usr/bin/env bash
# Generate Hyprland Lua from a loaded workplace, and manage the loader
# snippet that makes Hyprland pick the generated file up.

# Render the generated Lua for the currently loaded workplace to stdout.
lua_generate() {
  local slug=$1
  local mon ws app field regex rules

  printf -- '-- Generated by hyprworkplace. Do not edit by hand.\n'
  printf -- '-- Workplace: %s\n' "${HW_META[name]:-$slug}"
  if [[ -n ${HW_META[description]:-} ]]; then
    printf -- '-- %s\n' "${HW_META[description]}"
  fi
  printf -- '-- Change it with:   hyprworkplace edit %s\n' "$slug"
  printf -- '-- Re-apply it with: hyprworkplace apply %s\n\n' "$slug"

  if [[ -n ${HW_META[gdk_scale]:-} ]]; then
    printf 'hl.env("GDK_SCALE", %s)\n\n' "$(lua_quote "${HW_META[gdk_scale]}")"
  fi

  printf -- '-- Monitors that are not part of this workplace\n'
  if [[ ${HW_META[unlisted]:-auto} == disable ]]; then
    printf 'hl.monitor({ output = "", disabled = true })\n\n'
  else
    printf 'hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })\n\n'
  fi

  printf -- '-- Monitors\n'
  for mon in "${HW_MONITORS[@]}"; do
    if [[ ${HW_MON[$mon|enabled]:-true} == false ]]; then
      printf 'hl.monitor({ output = %s, disabled = true })\n' "$(lua_quote "$mon")"
      continue
    fi

    rules="output = $(lua_quote "$mon")"
    rules+=", mode = $(lua_quote "${HW_MON[$mon|mode]}")"
    rules+=", position = $(lua_quote "${HW_MON[$mon|position]:-auto}")"
    rules+=", scale = $(lua_value "${HW_MON[$mon|scale]:-1}")"

    if [[ ${HW_MON[$mon|transform]:-0} != 0 ]]; then
      rules+=", transform = ${HW_MON[$mon|transform]}"
    fi
    if [[ ${HW_MON[$mon|vrr]:-0} != 0 ]]; then
      rules+=", vrr = ${HW_MON[$mon|vrr]}"
    fi
    if [[ -n ${HW_MON[$mon|mirror]:-} ]]; then
      rules+=", mirror = $(lua_quote "${HW_MON[$mon|mirror]}")"
    fi
    if [[ -n ${HW_MON[$mon|bitdepth]:-} ]]; then
      rules+=", bitdepth = $(lua_value "${HW_MON[$mon|bitdepth]}")"
    fi

    printf 'hl.monitor({ %s })\n' "$rules"
  done

  if ((${#HW_WS_IDS[@]} > 0)); then
    printf -- '\n-- Workspaces\n'
    for ws in "${HW_WS_IDS[@]}"; do
      printf 'hl.workspace_rule({ workspace = %s, monitor = %s })\n' \
        "$(lua_quote "$ws")" "$(lua_quote "${HW_WS[$ws]}")"
    done
  fi

  if ((${#HW_APPS[@]} > 0)); then
    printf -- '\n-- Apps\n'
    for app in "${HW_APPS[@]}"; do
      field=$(app_match_field "$app")
      regex=$(app_match_regex "$app")
      printf 'o.window({ %s = %s }, { workspace = %s })\n' \
        "$field" "$(lua_quote "$regex")" \
        "$(lua_quote "${HW_APP[$app|workspace]}")"
    done
  fi
}

# Write the generated Lua atomically.
lua_write() {
  local slug=$1 tmp
  mkdir -p "$HW_STATE_HOME"
  tmp=$(mktemp "$HW_STATE_HOME/.workplace.lua.XXXXXX") ||
    die "could not create a temporary file in $HW_STATE_HOME"
  if ! lua_generate "$slug" >"$tmp"; then
    rm -f "$tmp"
    die "failed to generate Lua for '$slug'"
  fi
  mv -f "$tmp" "$HW_GENERATED_LUA" ||
    die "could not write $HW_GENERATED_LUA"
}

loader_file() {
  printf '%s/monitors.lua' "$HW_HYPR_CONFIG"
}

loader_installed() {
  local file
  file=$(loader_file)
  [[ -f $file ]] && grep -qF -- "$HW_LOADER_BEGIN" "$file"
}

# A Lua expression for the generated file, keeping $HOME portable.
_loader_lua_path() {
  if [[ $HW_GENERATED_LUA == "$HOME"/* ]]; then
    printf 'os.getenv("HOME") .. %s' "$(lua_quote "${HW_GENERATED_LUA#"$HOME"}")"
  else
    lua_quote "$HW_GENERATED_LUA"
  fi
}

loader_snippet() {
  cat <<EOF
$HW_LOADER_BEGIN
-- Loads the workplace generated by hyprworkplace. Managed automatically,
-- remove this block with: hyprworkplace uninstall
local hyprworkplace_path = $(_loader_lua_path)
local hyprworkplace_file = io.open(hyprworkplace_path, "r")
if hyprworkplace_file then
	hyprworkplace_file:close()
	dofile(hyprworkplace_path)
end
$HW_LOADER_END
EOF
}

# Append the loader snippet to monitors.lua unless it is already there.
# It goes last so that it overrides whatever the user configured before.
loader_ensure() {
  local file
  file=$(loader_file)

  if loader_installed; then
    return 0
  fi

  [[ -d $HW_HYPR_CONFIG ]] ||
    die "Hyprland config directory not found: $HW_HYPR_CONFIG"

  if [[ -f $file ]]; then
    cp -p "$file" "$file.bak.$(date +%s)" || die "could not back up $file"
    printf '\n' >>"$file"
  fi

  loader_snippet >>"$file" || die "could not write $file"
  ok "Installed the hyprworkplace loader into $file"
}

# Remove the loader snippet again.
loader_remove() {
  local file tmp
  file=$(loader_file)

  if ! loader_installed; then
    return 0
  fi

  cp -p "$file" "$file.bak.$(date +%s)" || die "could not back up $file"

  tmp=$(mktemp) || die "could not create a temporary file"
  if ! awk -v b="$HW_LOADER_BEGIN" -v e="$HW_LOADER_END" '
        index($0, b) { skip = 1 }
        !skip { print }
        index($0, e) { skip = 0 }
      ' "$file" >"$tmp"; then
    rm -f "$tmp"
    die "could not rewrite $file"
  fi

  mv -f "$tmp" "$file" || die "could not rewrite $file"
  ok "Removed the hyprworkplace loader from $file"
}
